package emoji

enum class Emoji (
    val emoji: String,
        ) {
    FACE_EXHALING("\uD83D\uDE2E\u200D\uD83D\uDCA8"),
    BEAMING_FACE_WITH_SMILING_EYES("\uD83D\uDE01"),
    MONEY_WITH_WINGS("\uD83D\uDCB0"),
    DOLLAR_BANKNOTE("\uD83D\uDCB5"),
    MONEY_BAG("\uD83D\uDCB0"),
    RECEIPT("\uD83E\uDDFE"),
    ID_BUTTON("\uD83C\uDD94"),
    PERSON_SHRUGGING("\uD83E\uDD37"),
    FACE_WITH_MONOCLE("\uD83E\uDDD0"),
    MAGNIFYING_GLASS_TILTED_LEFT("\uD83D\uDD0D"),
    GREEN_CIRCLE ("\uD83D\uDFE2"),
    YELLOW_CIRCLE ("\uD83D\uDFE0"),
    RED_CIRCLE ("\uD83D\uDD34"),
}
